### ISSUE TITLE
Return Addresses 

### ISSUE THREAD

**Issue by Wrath-debug** [btbd/wpp#1]
so I have been trying to implement this method on other driver (ndis.sys), but I can't understand the return address.
how did you find it for disk.sys and mountmgr.sys ?

Thanks in advance

**Comment by btbd** [comment]
@Wrath-debug I am using the disk driver as an example. Let's take a look at its DeviceControl and see where it uses WPP tracing:

![image](https://user-images.githubusercontent.com/22239674/84555340-56fd7f80-acea-11ea-8810-2918ed9bfa35.png)

We see it calls WPP_SF_Dqq:

![image](https://user-images.githubusercontent.com/22239674/84555389-a17efc00-acea-11ea-89db-d1410870a0d1.png)

And here is where we see it call `pfnWppTraceMessage`, which is the function pointer we hook since it resides in a data section.

Thus, the laziest way to check if the correct function called our hook it is to simply trace two return addresses back and check if it's equal to (inside DiskDeviceControl):

![image](https://user-images.githubusercontent.com/22239674/84555374-8c09d200-acea-11ea-8cd0-1aaf1cab466f.png)

Which is how this signature was generated:

![image](https://user-images.githubusercontent.com/22239674/84555603-ab552f00-aceb-11ea-902b-224b640d37c6.png)

**Comment by Wrath-debug** [comment]
Thanks, I understood the concept now. However, ndis.sys looks a bit different.
They don't initialize  WmiTraceMessage
![1](https://user-images.githubusercontent.com/54267469/84567955-8f4d9e00-ad7c-11ea-977e-d228c024fb69.PNG)
Instead they use an export for WmiTraceMessageVa as in void function
![3](https://user-images.githubusercontent.com/54267469/84567982-c58b1d80-ad7c-11ea-9230-87d131d4cbe4.PNG)
and inside device controller they first call WmiTraceMessageVa then return with WppAutoLogTrace 
![2](https://user-images.githubusercontent.com/54267469/84568087-58c45300-ad7d-11ea-9e76-8ebed80b243f.PNG)
in this case we should hook WppAutoLogTrace instead of WmiTraceMessage
and return address will be at 74 29 48 8B 0D ? ? ? ? 45 8D 4F 17 
correct ?

**Comment by btbd** [comment]
@Wrath-debug Unfortunately you can't hook WppAutoLogTrace since it's an import and ndis' IAT is protected by PG. Likewise, ndisWppFastTraceMessage simply calls the WmiTraceMessageVa import. You will have to use a different method to hook its DeviceControl.
